import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <nav className="menu-bar bg-gray-800 text-white p-4">
          {/*<button className="font-bold" onClick={() => console.log('toggleMenu')}>Menu</button>*/}
          <div id="fullMenu" className="hidden menu-bar expanded">
            <p>Log-In</p>
            <p>Sign in</p>
            <p>Subscribe</p>
          </div>
        </nav>
        <div className="flex-grow">
          {children}
        </div>
      </body>
    </html>
  );
}
