"use client";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {Menu} from "../../components/menu";
import Script from 'next/script';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';


const inter = Inter({subsets: ["latin"]});

{/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <head>
            <title>Title</title>
            <Script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js"
                    integrity="sha512-u3fPA7V8qQmhBPNT5quvaXVa1mnnLSXUep5PS1qo5NRzHwG19aHmNJnj1Q8hpA/nBWZtZD4r4AX6YOt5ynLN2g=="
                    crossOrigin="anonymous" referrerPolicy="no-referrer"></Script>
            <meta name="viewport" content="initial-scale=1, width=device-width"/>
        </head>

        <body className="min-h-screen flex flex-col">
        <Menu/>
        <Container fixed>
            <Box sx={{bgcolor: '#cfe8fc', height: '50vh'}}>
                {children}
            </Box>
        </Container>
        </body>
        </html>
    );
}
